### ISSUE TITLE
How do I push a dynamic tag

### ISSUE THREAD

**Issue by paulwilton** [palantir/gradle-docker#109]
I can push latest tag, but I want to be able to push a dynamically generated tag to a private repo

```
docker {
    name 'my.private.registry/' + project.artifactName
    tags 'latest', "$project.version"
    dependsOn tasks.build
}

task pushDockerTags() {
    tasks["dockerPush$project.version"]
    dependsOn docker
}

afterReleaseBuild.dependsOn pushDockerTags
```
I get the following error:
A problem occurred evaluating root project 'my-artifactName'.
> Task with name 'dockerPush0.0.1-SNAPSHOT' not found in root project 'my-project-name'.

Is this possible ?
thanks for help.

**Comment by markelliot** [comment]
For that configuration there should be a task that's auto-generated called dockerPushLatest, which you can refer to as something like:

    afterReleaseBuild.dependsOn tasks['dockerPushLatest']

**Comment by paulwilton** [comment]
Hi Mark -  I thought from the docs that my task "dockerPush$project.version" was autogenerated by the tags command in the docker task ?
given I have 
`tags "$project.version"`
which evaluates in my case above to 
`tags 0.0.1-SNAPSHOT`
autogenerating a task:
`dockerPush0.0.1-SNAPSHOT`

**Comment by markelliot** [comment]
Sorry, you're correct. Could you list the tasks on this project and check that there is in fact a dockerPush0.0.1-SNAPSHOT task that shows up in the task list?

**Comment by paulwilton** [comment]
i did gradlew tasks and get this:
```
Docker tasks
------------
docker - Builds Docker image.
dockerClean - Cleans Docker build directory.
dockerfileZip - Bundles the configured Dockerfile in a zip file
dockerPrepare - Prepares Docker build directory.
dockerPush - Pushes named Docker image to configured Docker Hub.
dockerPush0.0.1-SNAPSHOT - Pushes the Docker image with tag '0.0.1-SNAPSHOT' to configured Docker Hub
dockerPushLatest - Pushes the Docker image with tag 'latest' to configured Docker Hub
dockerTag - Applies all tags to the Docker image.
dockerTag0.0.1-SNAPSHOT - Tags Docker image with tag '0.0.1-SNAPSHOT'
dockerTagLatest - Tags Docker image with tag 'latest'
```

so the task seems to be there, so wonder why it cannot be found at build time

**Comment by markelliot** [comment]
Yeah, it seems more like this is a Gradle side thing w/r/t getting the task. What happens if try to execute ./gradlew dockerPush0.0.1-SNAPSHOT ?

**Comment by paulwilton** [comment]
yes that works..  so I need to work out why gradle cant find the task  when running

**Comment by paulwilton** [comment]
okay this seems to work..if I add the dynamic task to project.afterEvaluate
```
project.afterEvaluate {
    pushDockerTags.dependsOn tasks["dockerPush$project.version"]
}

task pushDockerTags() {
    dependsOn dockerPush
}
```

**Comment by paulwilton** [comment]
okay maybe not, cant do clean or release with this method. Its proving very painful to an automated release, automated versioning and tagging / pushing.
Was so trivial with maven..  have tried 5 different gradle plugins now for versioning and releasing docker images  :(
