### ISSUE TITLE
Not working with gradle 3.3

### ISSUE THREAD

**Issue by snwiem** [palantir/gradle-docker#110]
Configuration used from https://plugins.gradle.org/plugin/com.palantir.docker

buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.palantir.gradle.docker:gradle-docker:0.12.0"
  }
}

apply plugin: "com.palantir.docker"

Error Message:
17:56:25.999 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
17:56:25.999 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:56:26.001 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
17:56:26.001 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:56:26.001 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org/gradle/api/internal/component/UsageContext
17:56:26.002 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > org.gradle.api.internal.component.UsageContext
17:56:26.002 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
17:56:26.002 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
17:56:26.002 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
17:56:26.002 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
17:56:26.002 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
17:56:26.002 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] 
17:56:26.002 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 2.289 secs

**Comment by uschi2000** [comment]
Check the release notes, please. 0.12.0 requires 3.4-rc-1.
