### ISSUE TITLE
Be able to input Directory in files

### ISSUE THREAD

**Issue by aclairekeum** [palantir/gradle-docker#115]

**Comment by aclairekeum** [comment]
was hoping if there's a way to keep the directory format without unpacking it into a list of files in build/docker

**Comment by uschi2000** [comment]
Can you expand on this: what's the configuration you're trying and in what
way does it not behave as expected?

**Comment by aclairekeum** [comment]
Here's an example.

When we have something like 
docker {
...
files 'dirName'
}

Files in dirName directory gets unpacked into a list of files under build/docker. However, there are some use cases I could think of, where we keep multiple scripts together, or jar files together in a directory, in which would allow us to simply copy that directory into the docker image. There's a workaround to this, which is by creating another layer of directory under a directory- 

Thought that 'files' maintaining its format (if is a directory, whole directory be included in docker context and if a file, just a file be included in) would be useful.

**Comment by uschi2000** [comment]
Agree. Are you willing to provide a failing test
in PalantirDockerPluginTests?

**Comment by aclairekeum** [comment]
Yes sure. I'll create a PR soon.

**Comment by uschi2000** [comment]
Closed by https://github.com/palantir/gradle-docker/pull/123
