### ISSUE TITLE
Docs: dependsOn to files

### ISSUE THREAD

**Issue by damianoneill** [palantir/gradle-docker#118]
I recently upgraded to the latest version of the plugin.  I noted the move from dependsOn to files. 

I am using spring boot in a multi project.  

My config looks like 

```
docker {
    name "app:${project.version}"
    dependsOn tasks.jar, tasks.bootRepackage
}
```

This previously copied the src/main/resources content across (and maintained the directory structure src/main/resources/...). 

My config now looks like below, with everything below src/main/resources in the build/docker directory, ideally I'd like them in build/docker/src/main/resources/ ...

```
docker {
    name "app:${project.version}"
    files tasks.jar.outputs, tasks.bootRepackage.outputs, 'src/main/resources'
}
```

Is there a better solution for getting the src/main/resources across and maintaining the directory structure?  

Thanks.

**Comment by uschi2000** [comment]
Hej. We removed some of the hidden/magical configuration with the goal of making the docker build context easier to understand. The contract is: the plugin copies the declared `docker.dockerfile` as well as all files declared via the `docker.files` copyspec:
```
            prepare.with {
                with ext.copySpec
                from(ext.resolvedDockerfile) {
                    rename { fileName ->
                        fileName.replace(ext.resolvedDockerfile.getName(), 'Dockerfile')
                    }
                }
                into dockerDir
            }
```
So what you're doing looks good. I don't quite follow what you mean by `My config now looks like below, with everything below src/main/resources in the build/docker directory, ideally I'd like them in build/docker/src/main/resources/ ...`, can you elaborate?

**Comment by damianoneill** [comment]
Hi Robert thanks for coming back so quickly. 

This was my previous directory structure 

build/docker/src/main/resources/someresources

Now its 

build/docker/someresources

Ideally I'd like a way to maintain the 'src/main/resources' part of what gets copied across.

I wasn't sure if there was tasks.xxx.xxx option that could be used for src/main/resources or some other gradle mechanism.  

Apologies I'm not a gradle expert.

**Comment by uschi2000** [comment]
I see you can get access to the underlying copyspec via `docker.copySpec` and do something like this (untested, syntax is probably a bit broken, but you get the idea):
```
docker {
    name "app:${project.version}"
    files tasks.jar.outputs, tasks.bootRepackage.outputs
}
docker.copySpec
  .from('src/main/resources')
  .into('src/main/resources')
```
see https://docs.gradle.org/current/userguide/working_with_files.html

**Comment by uschi2000** [comment]
Closing for now, let me know if that doesn't work.
