### ISSUE TITLE
Gradle 3 Support For Docker-Run

### ISSUE THREAD

**Issue by derenrich** [palantir/gradle-docker#119]
When trying to use docker-run under gradle 3 I get the error

>  `No service of type StyledTextOutputFactory available in ProjectScopeServices.`

Google suggests this is a compatibility issue with gradle 3.

**Comment by uschi2000** [comment]
Which version of Gradle, exactly?

**Comment by derenrich** [comment]
3.3

**Comment by uschi2000** [comment]
See https://github.com/palantir/gradle-docker/releases/tag/0.12.0 .
Plugin requires >=3.4
