### ISSUE TITLE
Define Tags Based on Another Task

### ISSUE THREAD

**Issue by pluttrell** [palantir/gradle-docker#125]
I use another task (`id "com.zoltu.git-versioning" version "3.0.2"`) to set the `project.version` dynamically based on Git tags. 

But it doesn't set the `project.version` until after the first phase of Gradle processing. So if I set the `tags` for `id "com.palantir.docker" version "0.12.0"` as such:
```
docker {
    tags project.version
}
```
I end up with tagging the image with `unspecified`. 

Is there a way to set the tags after Gradle's first phase?

I suspect that I need to add a `doFirst` closure such as this:

```
dockerPrepare.doFirst {
     println "dockerPrepare.doFirst, project.version: " + project.version
}
```

but how do I update planitir's `tags` property?

**Comment by uschi2000** [comment]
This is difficult since we need to generate tasks from the version. Why can
you not set the project version at build script evaluation time?

**Comment by pluttrell** [comment]
I ended up forcing the `com.zoltu.git-versioning` plugin to generate the version at configuration time, which resolved this.

**Comment by awallat** [comment]
I had the same problem when using the [jgitver-plugin](https://github.com/jgitver/gradle-jgitver-plugin). The version was calculated after the dynamic tasks (for handling defined tags) were created. My solution was to create the task manually:

```groovy
afterEvaluate {
    Exec tagGitVersion = project.tasks.create('dockerTagGitVersion', Exec, {
        group = 'Docker'
        description = "Tags Docker image with tag '${version}'"
        workingDir "${project.buildDir}/docker"
        commandLine 'docker', 'tag', "my-project", "my-project:${version}"
    })
    dockerTag.dependsOn tagGitVersion

}
```
