### ISSUE TITLE
Output the docker output when building

### ISSUE THREAD

**Issue by podollb** [palantir/gradle-docker#127]
When building a docker image I'd like to have a way to turn on verbosity or set a log level to see all the work that is being done as it builds the docker image (unless this is already possible in some way?).

**Comment by mnesbitt** [comment]
@podollb what about:

gradle docker --info

**Comment by ghost** [comment]
Is there a way to turn it on permanently in the build script?

**Comment by pkoenig10** [comment]
Don't think that is currently possible. There is an open gradle issue for it: https://github.com/gradle/gradle/issues/1010
