### ISSUE TITLE
Problems using Plugin with Gradle 3.4 and 3.4.1

### ISSUE THREAD

**Issue by qux42** [palantir/gradle-docker#131]
I have problems using the pluging with gradle 3.4
With gradle 3.3 it works.

**Comment by uschi2000** [comment]
Thanks for flagging. It would be helpful if you could provide a little more
detail on the issues you're seeing.

**Comment by qux42** [comment]
Trying to sepperate the problem, I realized that I used a older version of the plugin.
With the newest Version everything works fine.
Sorry for the false alarm and thanks for the quick help :)

**Comment by uschi2000** [comment]
Great.
