### ISSUE TITLE
Deprecate docker-compose plugin?

### ISSUE THREAD

**Issue by markelliot** [palantir/gradle-docker#133]
Docker-compose supports reading parameters from a `.env` file, which would allow for the same kind of templating as is being done with the docker configuration. I don't think we're using the docker-compose plugin effectively right now because the publishing setup is never happening and so the consumption is using bogus artifacts.

I'd propose we simply deprecate the whole thing in favor of the `.env` file.

**Comment by uschi2000** [comment]
+1

**Comment by derenrich** [comment]
Why not just extend the existing plugin? Do we have to deprecate a plugin that is in very wide use?

**Comment by markelliot** [comment]
I'm not sure the docker-compose plugin is in such wide use, and where we've observed use it's often not used correctly (or at least, not as intended), which generally leads to both bad build perf and very hard to manage setups.

**Comment by derenrich** [comment]
Simple github-search-foo suggests around 150 projects using the docker-compose plugin?

**Comment by jnm-ronquillo** [comment]
Does anyone know the proper way to use docker-compose plugin in a multimodule Gradle Project? For now I included the plugin only on one of the modules.

**Comment by djechelon** [comment]
I don't fully agree with the topic. While I agree that the env file supersedes the main purpose of the plugin (template handling), having a Gradle task to start up docker-compose is very useful from the plugin development point of view (e.g. if you are working on a Gradle build that requires testing on a docker stack.... just as an example)
