### ISSUE TITLE
Please publish 0.14.0 to https://plugins.gradle.org/

### ISSUE THREAD

**Issue by xmlking** [palantir/gradle-docker#146]
Please publish 0.14.0 to https://plugins.gradle.org/ sothat we can use :
```
plugins {
    id 'com.palantir.docker' version '0.14.0 '
}
```

**Comment by xmlking** [comment]
please publish 0.14.0

**Comment by uschi2000** [comment]
want to make a PR to this effect, @xmlking ?

**Comment by xmlking** [comment]
I am just learning how to publish plugins
According this link https://plugins.gradle.org/docs/submit , who published this plugin first, should already have "API key".  can you provide the key ? 
Thanks

**Comment by uschi2000** [comment]
Hej @xmlking  -- I just realized that this is probably a difficult thing for you to do given the access controls, sorry for making this suggestion. I will try to get this done at some point, but can't really promise an ETA. In the mean time, you should be able to use the explicit Maven coordinate to apply the plugin, right?

**Comment by xmlking** [comment]
Should I use something like this?
```grooby
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven ("https://plugins.gradle.org/m2/" )
    }
    dependencies {
        classpath("gradle.plugin.com.palantir.gradle.docker:gradle-docker:0.14.0")
    }
}
```
I also don't see 0.14.0 here: 
https://palantir.bintray.com/releases/com/palantir/gradle/docker/gradle-docker/

**Comment by uschi2000** [comment]
0.17.0 is available on bintray/jcenter. working on the plugin portal now.

**Comment by uschi2000** [comment]
0.17.2 available on plugin portal
