### ISSUE TITLE
add static content to docker image 

### ISSUE THREAD

**Issue by Xsires** [palantir/gradle-docker#161]
Hi could you please help me with my problem

I would like to add static content (configuration files) to docker image
./gradlew docker  
fails with

`ADD failed: stat /var/lib/docker/tmp/docker-builder157707131/config/my-config.xml: no such file or directory`

when i try to do it with native "docker build" command, it is work well

build.gradle

```
docker {
    name "ru.xsires/docker-image:${project.version}"
    buildArgs(['CONFIG_NAME': "my-config.xml"])
}
```

Dockerfile

```
FROM java:8u111
ARG CONFIG_NAME
ADD config/$CONFIG_NAME config/$CONFIG_NAME
```

example

https://github.com/Xsires/docker-image

**Comment by uschi2000** [comment]
Please check the `docker.files` configuration option in the README. It instructs the plugin to copy files into the Docker build context (here: `/var/lib/docker/tmp/docker-builder157707131/`) before executing `docker build`.

**Comment by Xsires** [comment]
@uschi2000  Thank you very much, I understood how it works
