### ISSUE TITLE
How can I add all the files in a folder to Dockerfile context without specifying one by one ?

### ISSUE THREAD

**Issue by tanvn** [palantir/gradle-docker#187]
I have a folder to store the config files for my application.
When the number of the files increases, I think it would be better to add the whole folder
to the context instead of specifying one by one in `files`.
I have tried to use copySpec by it doesn't seem to be working.

**Comment by pkoenig10** [comment]
@tanvn can you post your configuration?

**Comment by tanvn** [comment]
My project's structure is like below :
```
-project
 |-src
 |-conf-|
 	    |-a.properties
 	    |-b.properties
 	    |-c.properties
 |
 |-build.gradle
```

 In my build.gradle, I have 

```
   docker {
    dependsOn build
    dockerfile file('docker/Dockerfile')
    name "${project.group}/${bootJar.baseName}"
    files bootJar.archivePath, "conf/a.properties", "conf/b.properties", "conf/c.properties"
    buildArgs(['JAR_FILE': "${bootJar.archiveName}"])
}
```
I mean, if I have many files in **conf**, is there any more convenient way ( a more concise  expression) to add all the files into the build context ?

**Comment by aidoan** [comment]
@tanvn try this one:
```
docker {
    ...
    copySpec.with {
        from('.') {
            include 'conf/**'
            into '.'
        }
    }
   ...
}
```

**Comment by tanvn** [comment]
Thank you so much !
