### ISSUE TITLE
Configuring a second Docker container

### ISSUE THREAD

**Issue by voddan** [palantir/gradle-docker#193]
How do I configure a second Docker container? 

I need container A to be run for one some tests, and container B to be run for other tests in the same project. Container A is configured with `dockerRun {...}`, but where do I put parameters for Container B?

Thanks!

**Comment by markuskeunecke** [comment]
I was facing a similar problem for building several docker images in a multi project build. My approach was to create a separate project for each image to build.

**Comment by pkoenig10** [comment]
This plugin is targeted for creating docker images from a gradle project.

If you need to run docker containers as part of a test, I encourage you to look at [docker-compose](https://docs.docker.com/compose/). We even have a nifty gradle plugin for exactly this use case in [docker-compose-rule](https://github.com/palantir/docker-compose-rule)!
