### ISSUE TITLE
tags are not applied to the image produced

### ISSUE THREAD

**Issue by aram535** [palantir/gradle-docker#200]
Hi, 

I'm using 0.20.1 and the following script does not seem to tag the images with the additional tags requested:

```
docker {
    name "${project.group}/${bootJar.baseName}:${project.version}"
    tags  "latest"
    dockerfile file('Dockerfile')
    files bootJar
    buildArgs(['JAR_FILE': "${bootJar.archiveName}", 'BUILD_VERSION': "${project.version}"])
}
```
I also tried 
```
tags project.version, "latest" 
```
the project.version is tagged properly, however the 'latest' tag is nowhere to be found. 

Thanks.

Gradle Verision: 4.9
OS: CentOS 7.5 64-bit 
JRE/JDK: Oracle 1.8.0_181

**Comment by steventwheeler** [comment]
@aram535 I have the opposite problem, but it might be a solution for you. 

Using this configuration I get both the requested tag name plus `latest` even though I don't want a `latest` tag.

```
docker {
    name("${project.group}/${project.name}")
    tags(project.version)
}
```

I am not very familiar with Groovy but I looked over the code and can't figure out why the `latest` gets added even when not requested.

**Comment by aram535** [comment]
@steventwheeler that's docker doing it.  If you tag a source:tag destination  (without a tag, it'll tag it as "latest").  Just give it the version number and it should stop putting latest on it.

I have an easy workaround (external) but I'll pull the code and see where the problem is and see if I can do a pull-request back to fix it.

To confirm try this: 

```
# docker pull alpine:3.8 
# docker images 
... 
# docker tag alpine:3.8 alpine 
# docker images
... 

```
you should see a new alpine:latest show up.

**Comment by easycoder666** [comment]
try the **dockerTag** task
`gradle clean build dockerTag`

**Comment by aram535** [comment]
Hah, thanks for that ... 👍
if I had actually downloaded the code and looked at it, I'm sure it would have been clear.
