### ISSUE TITLE
docker build --force-rm

### ISSUE THREAD

**Issue by richard-pare** [palantir/gradle-docker#207]
How can I  put "--force-rm" option in for docker build execution?

I uses the version 0.20.1

**Comment by jomach** [comment]
same here. I want to use --rm on the build

**Comment by pkoenig10** [comment]
When running `docker build` the default is `--rm=true` (https://github.com/moby/moby/pull/4292). So intermediate containers will be removed as long as the build is successful.

Given that build failures should be rare, and that intermediate containers will be removed once the build is successful, I don't think we're going to add this feature to this plugin.

**Comment by rubencaro** [comment]
Would this fix https://github.com/palantir/gradle-docker/issues/240 ?
