### ISSUE TITLE
Change default log level of docker output

### ISSUE THREAD

**Issue by dherges** [palantir/gradle-docker#216]
Related to #127 

```bash
$ gradle docker
```

No output

---

```bash
$ gradle docker --info
```

Prints the output from `docker build` but also shows a lot of other unrelated output.

---

What do you think about changing the default stdout capturing to [LogLevel.LIFECYCLE](https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level)?

When I run `docker build` on my shell, I see the progress output of the docker build steps by default. When I run `docker gradle`, I don't see it. I think it's a good idea to give the user feedback about the progress so that the docker steps are printed:

```
Sending build context to Docker daemon  25.73MB
Step 1/9 : FROM java:openjdk-8-jdk
(...and so on...)
```

https://github.com/palantir/gradle-docker/blob/develop/src/main/groovy/com/palantir/gradle/docker/PalantirDockerPlugin.groovy#L118

**Comment by pkoenig10** [comment]
`LIFECYCLE` is more appropriate for logging progress of the _Gradle_ build. From the [Gradle docs](https://docs.gradle.org/current/userguide/logging.html):
> There are two Gradle-specific log levels, in addition to the ones you might normally see. Those levels are QUIET and LIFECYCLE. The latter is the default, and is used to report build progress.

Logging docker build progress at the lifecycle level is probably too noisy to be a default.

Ideally this would be something you configure on a per-task basis. But it seems that is not yet possible:
https://github.com/gradle/gradle/issues/1010

**Comment by pkoenig10** [comment]
Closing as wont-fix. Configuring per-task log levels is being tracked in the linked Gradle issue.

**Comment by dherges** [comment]
Sounds reasonable!
