### ISSUE TITLE
how to build the image with a dynamic tag use shell？

### ISSUE THREAD

**Issue by dongze1213** [palantir/gradle-docker#218]
i has tried with dockerTag , it is not work.

**Comment by pkoenig10** [comment]
You can use variables to define the `tag` values when configuring the docker plugin.

**Comment by arulrajnet** [comment]
I think he asked about how we can pass tag name from gradle command

```
docker {
  def imageName = 'myorg/module'
  def tagName = version
  if(project.hasProperty('dockerTagName')){
    tagName = dockerTagName
  }
  name imageName
  tag 'hub', "$imageName:$tagName"
  dockerfile file('Dockerfile')
  files tasks.distTar.outputs
}
```

Then `gradle -PdockerTagName=my-own-tag-name dockerTag` This how you can pass the dynamic name from shell.
