### ISSUE TITLE
version number question

### ISSUE THREAD

**Issue by constructivetim** [palantir/gradle-docker#224]
I am using 

plugins {
  id "com.palantir.docker" version "0.21.0"
}

is this the correct version?  I only ask because the document at https://github.com/palantir/gradle-docker says that "tags" is deprecated, and "tag" should be used, but 0.21.0 refuses "tag", but is happy with "tags":

> Could not find method tag() for arguments [version] on object of type com.palantir.gradle.docker.DockerExtension.

"tags" works ok locally, but fails to push the tags.  i have seen some issues have been fixed with respect to this.

thanks for helping out 

tim

**Comment by pkoenig10** [comment]
`tag` takes two arguments, a task name and a docker tag. Here's the example from the [README](https://github.com/palantir/gradle-docker#docker-plugin):
```
docker {
    tag 'myRegistry', 'my.registry.com/username/my-app:version'
}
```
