### ISSUE TITLE
generateDockerCompose should replace generated docker-compose if already exists

### ISSUE THREAD

**Issue by gregakinman** [palantir/gradle-docker#226]
## What happened?

If a docker-compose file already exists, `generateDockerCompose` does not replace it.

## What did you want to happen?

`generateDockerCompose` should replace a docker-compose file if one already exists.

**Comment by pkoenig10** [comment]
I was able to reproduce this. The issue is that external dependencies are considered inputs but template tokens are not. So the docker-compose file will not get regenerated if the template tokens defined in the extension change.
