### ISSUE TITLE
Add `dockerLogin` task

### ISSUE THREAD

**Issue by markelliot** [palantir/gradle-docker#26]
Add a block to the `docker` config block that accepts multiple docker sites and credentials, e.g.:

```
docker {
    login {
        'hub.docker.com' {
            username System.env.USERNAME
            password System.env.PASSWORD
        }        
    }
...
```

`docker` and `dockerPush` must depend on `dockerLogin.

**Comment by chris060986** [comment]
Created a PR for this:
[Allow docker login to private repo before push #198](https://github.com/palantir/gradle-docker/pull/198)
But only for a single private docker repository.
