### ISSUE TITLE
Cannot apply docker-compose in a sub-project

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/gradle-docker#27]
The `generateDockerCompose` task resolves dependencies from the current project, so if you're applying the plugin in a Gradle sub-project, the task will fail if you have your dependencies defined in your root build.gradle. See: https://github.com/palantir/gradle-docker/blob/develop/src/main/groovy/com/palantir/gradle/docker/DockerComposePlugin.groovy#L41. Is this intended behavior? If not, perhaps we can change it to also include the root project's dependencies.

**Comment by uschi2000** [comment]
But it's the standard gradle model to define dependencies in the (sub-) project in which they are needed and consumed. Which alternative are you proposing?

**Comment by markelliot** [comment]
I think you should define your dependencies where they're actually used, the plugin behaves as expected, presently.

**Comment by michael-yx-wu** [comment]
That makes sense. Closing this out!
