### ISSUE TITLE
Support for multi-arch builds and manifests

### ISSUE THREAD

**Issue by gotson** [palantir/gradle-docker#298]
Hi,

Docker is now supporting multi-arch builds, along with manifest files. It would be nice for this plugin to handle those.

Thanks

**Comment by yuanjinyong** [comment]
I also hope this feature.

**Comment by rr-nick-tan** [comment]
looking forward for this feature as well

**Comment by shahbazshueb** [comment]
+1 for this feature.

**Comment by yuanjinyong** [comment]
Released [0.33.0](https://github.com/palantir/gradle-docker/releases/tag/0.33.0)
#470 
#528
