### ISSUE TITLE
Could not find method clean() for arguments [true] on project ':myproject'.

### ISSUE THREAD

**Issue by davidkbainbridge** [palantir/gradle-docker#44]
When attempting to use a dockerRun task with a definition such as:

```
dockerRun {
    name 'mycontainer'
    image 'org/name:0.1-prerelease'
    clean true
}
```

I get the following error

```
Could not find method clean() for arguments [true] on project ':myproject'.
```

**Comment by markelliot** [comment]
@mglazer

**Comment by markelliot** [comment]
Sorry, this option is only available on 0.7.0, which is building now.

**Comment by davidkbainbridge** [comment]
Thanks. Are you looking to expose other "run" options such as `tty` and `net`?

Additionally, supporting the setting of environment variables (in support of 12 factor app config) would be helpful too.

**Comment by mglazer** [comment]
Looks like 0.7.0 is up now, thanks. For the future, what's the best way of ensuring that the README is aligned with the current release?

**Comment by uschi2000** [comment]
Hmm, assuming you have regular-ish releases, that seems like an acceptable
edge case.

**Comment by markelliot** [comment]
I should've released shortly after accepting the PR, it just got away from me. Sorry!
