### ISSUE TITLE
Getting "failed to compute cache key: "/build/libs/..." not found: not found while building image

### ISSUE THREAD

**Issue by mkaberman** [palantir/gradle-docker#475]
## What happened?

I am getting "**_failed to compute cache key: "/build/libs/app-spring-0.0.1-SNAPSHOT.jar"not found: not found_** " while building docker image for my Spring Boot application using Gradle and Docker plugin. When I am building my image directly (using docker build) it builds and runs without any issues. 

My plugin definition:

  ```
docker {
     name "${project.name}:${project.version}"
     files 'app-spring.jar'
     buildArgs([BUILD_VERSION: project.version])
     noCache true
     }
```

My Dockerfile:

```
FROM amazonlinux:2
RUN yum install -y java-11-amazon-corretto

ARG BUILD_VERSION
ENV APP_HOME /apps/services


ARG JAR_FILE=build/libs/app-spring-${BUILD_VERSION}.jar
COPY ${JAR_FILE} ${APP_HOME}/app-spring.jar
EXPOSE 8080

CMD java \
   -Xms1024m -Xmx6000m \
   -Duser.timezone=UTC \
   ${JVMARGS} \
   -jar ${APP_HOME}/app-spring.jar


```
Docker build command 

`docker build --tag=app-spring:0.0.1-SNAPSHOT --build-arg BUILD_VERSION=0.0.1-SNAPSHOT .`

executes with no no issues, but gradle build `./gradlew docker` builds with the error: 

`**failed to compute cache key: "/build/libs/app-spring-0.0.1-SNAPSHOT.jar" not found: not found**`

## What did you want to happen?
`./gradlew docker` command should succeed and produce docker file

**Comment by mkaberman** [comment]
I changed my code to breakdown jar into layers, but still seeing similar problem. I am running Gradle v 7.1.1 and Java 11.

My Gradle file (relevant part):

```
task explodeJar {
    project.delete "$projectDir/build/dependencies"
	project.mkdir "$projectDir/build/dependencies"
	doLast {
	  exec {
      	workingDir "$projectDir/build/dependencies" 	
      	commandLine   "jar", "-xf", "../libs/${project.name}-${project.version}.jar"
      } 
    }
}	
	
docker {
     dependsOn(explodeJar)
     name "${project.name}:${project.version}"
     files 'payouts-spring.jar'
     buildArgs([BUILD_VERSION: project.version])
     }
```

My Dockerfile:

```
FROM amazonlinux:2
RUN yum install -y java-11-amazon-corretto

ARG BUILD_VERSION

ENV APP_HOME /apps/services



ARG DEPENDENCY=build/dependencies

COPY ${DEPENDENCY}/BOOT-INF/classes /app
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF


ENTRYPOINT ["java","-cp","app:app/lib/*","com.MyClass]
```

When I am running ./gradlew docker command : am getting error:

```
------
 > [5/5] COPY build/dependencies/META-INF /app/META-INF:
------
failed to compute cache key: "/build/dependencies/META-INF" not found: not found

```

**Comment by mkaberman** [comment]
The reason for my problem is because the plugin runs from build/docker directory and copies the Dockerfile there (it is indirectly mentioned in readme). So if my Dockerfile assumes that it is running from project's root directory it cannot find the files.  The way I solved the problem is to copy my jar file:
 `copySpec.from(tasks.bootJar.outputs.files.singleFile).into("/build/libs")`
 
It is not clear why the plugin cannot run from the project's root folder, but since I found the solution I am closing the issue.

**Comment by AlicanBalik** [comment]
> The reason for my problem is because the plugin runs from build/docker directory and copies the Dockerfile there (it is indirectly mentioned in readme). So if my Dockerfile assumes that it is running from project's root directory it cannot find the files. The way I solved the problem is to copy my jar file:
> `copySpec.from(tasks.bootJar.outputs.files.singleFile).into("/build/libs")`
> 
> It is not clear why the plugin cannot run from the project's root folder, but since I found the solution I am closing the issue.

Can you please paste your final `build.gradle` and `Dockerfile`? Thanks.
