### ISSUE TITLE
Files listed in 'files' are eagerly checked for existence

### ISSUE THREAD

**Issue by matthewrj** [palantir/gradle-docker#50]
My Dockerfile adds an artifact produced by the 'dist' task and so I have a task dependency on dist in the docker plugin configuration. However when I add that file to the 'files' property, Gradle throws and error saying the file doesn't exist before attempting to build anything. The file will exist once the dist task has completed.

**Comment by rmelick** [comment]
This was the same problem I had in #42 .  I worked around it by using the dependsOn method
