### ISSUE TITLE
How can I run several containers in a single build?

### ISSUE THREAD

**Issue by barthand** [palantir/gradle-docker#51]
Thanks for the plugin! 

I'm wondering whether it is possible to define tasks that each runs a different container? The problem is that there is no such class like `DockerRunTask` that could be extended, instead tasks like `dockerRun` are created in `DockerRunPlugin`

I was trying the following approach:

```
task runComposer() {
    dockerRun {
        name 'my-container'
        image 'composer/composer:php5'
        volumes '.': '/app'
        daemonize false
        command 'install'
    }

    dependsOn   "dockerRun"
}

task runHelloWorld() {
    dockerRun {
        name 'other-container'
        image 'hello-world'
        volumes '.': '/app'
        daemonize false
    }

    dependsOn   "dockerRun"
}
```

It seems though it isn't the valid approach as both tasks are configuring the same instance of `dockerRun` task, effectively overwriting the `dockerRun` configuration.

Any ideas?

Thanks!

**Comment by markelliot** [comment]
Sorry, the way this is written you can only have one dockerRun task per project. You can make new projects by declaring them and configuring them within your build.gradle, but the syntax proposed on this thread won’t work.
