### ISSUE TITLE
dockerTag task uses "docker tag --force" which is removed in Docker 1.12.x

### ISSUE THREAD

**Issue by hzuo** [palantir/gradle-docker#57]
see:
https://github.com/convox/rack/issues/781
https://github.com/docker/compose/issues/3651
https://forums.docker.com/t/docker-1-12-breaks-docker-tag-f-in-scripts/16992

**Comment by markelliot** [comment]
This was merged as part of #28 and released as part of 0.6.0, I think you may just need to upgrade your plugin version (latest = 0.8.0).
