### ISSUE TITLE
How can I use dockerPush<tag> with dependsOn?

### ISSUE THREAD

**Issue by artefactop** [palantir/gradle-docker#69]
I want to execute `dockerPushlatest` with dependsOn taks, my config is:

``` gradle
task testingDockerPushLatest(){
    dependsOn tasks.dockerPushlatest
}
```

But I'm getting this error:

``` sh
Could not get unknown property 'dockerPushlatest' for task set.
```

**Comment by liuhao92** [comment]
```
 project.afterEvaluate {
    yourTask.dependsOn DockerPush<tag>
 }
```

maybe this can work, i have the same problem before

**Comment by artefactop** [comment]
Now I get a different error

``` gradle
project.afterEvaluate {
    testingDockerPushLatest.dependsOn DockerPushlatest
}
task testingDockerPushLatest(){
    print "testingDockerPushLatest"
}
```

Error:

``` sh
Could not get unknown property 'DockerPushlatest' for root project 'myproject' of type org.gradle.api.Project.
```

**Comment by liuhao92** [comment]
Im sorry , DockerPush<tag> should be dockerPush<tag>, and the first letter of tag should be uppercase,   before you add the script above ,  you can run 'gradle tasks' to get all tasks,get the task name. and then add the script above.

**Comment by uschi2000** [comment]
The tasks are defined here: https://github.com/palantir/gradle-docker/blob/develop/src/main/groovy/com/palantir/gradle/docker/PalantirDockerPlugin.groovy#L127 . As you can see, that whole block is in afterEvaluate. And yes, `dockerPushLatest` should be a valid task name if you have a "latest" tag configured like this:

```
docker {
  // <snip>
  tags 'latest', 'snapshot'
}
```

**Comment by artefactop** [comment]
That works, thank you, final tasks:

``` gradle
docker {
  // <snip>
  tags 'latest'
}

project.afterEvaluate {
    generateDocker.dependsOn dockerPushLatest
}

task generateDocker(){
    dependsOn tasks.dockerPush
}

task release(){
    dependsOn tasks.generateDocker
}
```
