### ISSUE TITLE
docker disregards dependsOn clause for sourcing files

### ISSUE THREAD

**Issue by evmin** [palantir/gradle-docker#77]
I have explicitly defined the file that needs to be copied over to the build/docker directory using the 'file' clause.

Yet the file is supposed to be generated by the previous task, with the dependency defined by dependsOn clause:

`docker {
    name "${dockerImageName}"
    dockerfile 'src/main/docker/Dockerfile'
    dependsOn tasks.fatJar
    files  "files "build/packed/${jarFullName}""
}
`

I have a suspicion that the file is being checked prior the fatJar running. I get the following error:

'build/packed/fatJarName-2.1.3.jar' does not exist.

Do I miss something here? Wouldn't it be logical to build the file list after the dependsOn tasks have completed?

Indeed, when gradle runs the order seems to be:

:dockerfileZip
:compileJava
:processResources
:classes
:findMainClass
:jar
:bootRepackage
:fatJar
:dockerPrepare
:docker

Notice the dockerfileZip being the first. Wouldn't it be logical to move dockerfileZip to be placed immediately before dockerPrepare?

**Comment by markelliot** [comment]
The dependsOn here, probably incorrectly, isn't quite the same as normal dependsOn in task configuration. You can omit the files line in your config below as long as your task declares its outputs -- the dependsOn here will grab the outputs of dependent tasks.

**Comment by evmin** [comment]
Thank you - I think I understand the approach. Indeed, if dependsON is not provided, the resulting fatJar is not available to the docker task.

Yet the question is still there - why dockerfileZip needs to be run before compile task?
