### ISSUE TITLE
files not added to docker context

### ISSUE THREAD

**Issue by dsw2127** [palantir/gradle-docker#8]
Using the "files" method of the docker closure does not seem to have any effect.

I am trying to add a file like:
```
docker {
  name "myImage:${version}"
  files "myFile.txt"
}
```

In a Dockerfile that includes:
```
ADD myFile.txt /tmp/
```

but when running it I get the error:
```
Step 7 : ADD myFile.txt /tmp/
myFile.txt: no such file or directory
:myProject:docker FAILED
```

If I run dockerPrepare, I can see that while the Dockerfile appears in the build/ directory of the project, myFile.txt is not there.

**Comment by dsw2127** [comment]
The issue was a simple typo. Opened the PR with a fix and test: https://github.com/palantir/gradle-docker/pull/9

**Comment by markelliot** [comment]
Thanks for fixing.
