### ISSUE TITLE
Remote docker host?

### ISSUE THREAD

**Issue by andredasilvapinto** [palantir/gradle-docker#80]
Is it possible to use a remote docker host for building the image, like when setting the `docker.host` property on fabric8's docker maven plugin or this https://github.com/Transmode/gradle-docker#docker-remote-api ?

**Comment by uschi2000** [comment]
No, this is not currently possible.

**Comment by djechelon** [comment]
Is it possible to contribute by developing the feature and submitting a proper pull request?

Expecting something like

```

docker {
    host "ssh://docker-host" //or tcp:// etc
}
```
