### ISSUE TITLE
Docker-compose resolves dependencies during configuration time

### ISSUE THREAD

**Issue by henryptung** [palantir/gradle-docker#81]
While `generateDockerCompose` does need to use the dependencies from the `docker` configuration for further operation, I think it can do so during the task execution stage rather than project configuration stage. This accelerates project evaluation during the (common) case where `generateDockerCompose` is not being executed.

**Comment by uschi2000** [comment]
Yep, agreed. Don you want to give it a shot?

**Comment by stijndehaes** [comment]
This can get closed?
