### ISSUE TITLE
Cannot copy file into Docker image

### ISSUE THREAD

**Issue by ghost** [palantir/gradle-docker#83]
Hi

I am trying to build a simple docker image that requires a jar file to be copied from directory build/libs/ (the standard Gradle java plugin artefact output directory), but the docker task is reporting `lstat build/libs/myservice.jar: no such file or directory`. The file definitely exists at the given location, and using the command line `docker build -t x/y .` works OK.

Any ideas what I've missed?

Thx

**Comment by ghost** [comment]
I should add that there is no `.dockerignore` file, which seems to be the usual gotcha for this kind of problem! There is a `.gitignore`, but this should be irrelevant, right?

**Comment by uschi2000** [comment]
Hard to say without seeing a concrete example; do you have a link?

**Comment by ghost** [comment]
Here's a [minimal project](https://github.com/thirstybear/gradle-docker) to play with.

`./gradlew docker` fails
`docker build -t thirstybear/gradle-docker .` succeeds

I also noticed that `./gradlew build` (which the `docker` task is dependent on) no longer generates the jar file. It still fails even after running `./gradlew jar` separately.

**Comment by uschi2000** [comment]
the outputs of `dependsOn` task are copied into the docker context; I suspect that the `build` task doesn't define outputs, so you don't have your jars in the context. try `dependsOn jar`. granted, the docs could be better here.

**Comment by uschi2000** [comment]
Closing for now, feel free to re-open if this isn't resolved for you.

**Comment by varunmehta** [comment]
@thirstybear what was the solution that worked for you. In a similar boat for now.

**Comment by banywl** [comment]
I think I can solve it, it may be useful for you
```
docker {
...
 copySpec.from("build").into("build")
...
}

```
example：
```
docker {
    println("dir is: " + project.projectDir)
    name "${project.name}:${project.version}"
    dockerfile file('Dockerfile')
    buildArgs("BUILD_DATE": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"))
    copySpec.from("build").into("build")
}
```
